# IBM Data Analysis Capstone

### This notebook will be used to analyse traffic accident statistcs based on previous data

## 1.The Problem

The idea is to create a classification model capable to predict if there is significant probability of a colision to happen under a few pre-determined conditions.

The model can be used by traffic apps which might want to redirect clients to roads or junctions with less probablity of having an accident.

## 2.Data Description

The dataset used was provided by Coursera and it contains all collisions provided by SPD and recorded by Traffic Records, including all types of collision since 2004 to present.

It provides many columns with details on each type of colision. We excluded most of them and kept the columns that represents information data that would be available to some kind of traffic app, for example, in real time. The selected columns was:

SEVERITYCODE - This is our target, it represents the severity of each colision

ADDRTYPE - If it is a block or a junction

LOCATION - The colision address

JUNCTIONTYPE - The juntion type

WEATHER - How was the weather

ROADCOND - Road conditions

LIGHTCOND - Light conditions

INCDTTM - Timestamp of the colision

INCDTTM won't be used directly on the mode. Three features was created instead:

TIME - What time of the day it happened ('Late Night', 'Early Morning','Morning','Noon','Eve','Night')

WEEKEND - Was it weekend

HOLIDAY - was it a holiday

Thats is more significative than using the timestamp itself once we are bininng the time and checking if the accident occured on the days where the roads are usually busier.

## 3.Data Preparation

In [1]:
import pandas as pd
import numpy as np
from datetime import date 
import holidays

### Importing the Data

In [2]:
df_data=pd.read_csv('Data-Collisions.csv')
df_data.head()

d:\program files\python36\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,SEVERITYCODE,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,2,-122.323148,47.703140,1,1307,1307,3502005,Matched,Intersection,37475.0,...,Wet,Daylight,NaN,NaN,NaN,10,Entering at angle,0,0,N
1,1,-122.347294,47.647172,2,52200,52200,2607959,Matched,Block,NaN,...,Wet,Dark - Street Lights On,NaN,6354039.0,NaN,11,From same direction - both going straight - bo...,0,0,N
2,1,-122.334540,47.607871,3,26700,26700,1482393,Matched,Block,NaN,...,Dry,Daylight,NaN,4323031.0,NaN,32,One parked--one moving,0,0,N
3,1,-122.334803,47.604803,4,1144,1144,3503937,Matched,Block,NaN,...,Dry,Daylight,NaN,NaN,NaN,23,From same direction - all others,0,0,N
4,2,-122.306426,47.545739,5,17700,17700,1807429,Matched,Intersection,34387.0,...,Wet,Daylight,NaN,4028032.0,NaN,10,Entering at angle,0,0,N

### Removing unecessary Fields

In [3]:
df_data.drop(['X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY', 'REPORTNO', 'STATUS', 'INTKEY', 'EXCEPTRSNCODE', 
              'EXCEPTRSNDESC', 'SEVERITYDESC', 'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT', 'VEHCOUNT', 
              'INCDATE', 'SDOT_COLCODE', 'SDOT_COLDESC', 'INATTENTIONIND', 'UNDERINFL', 'PEDROWNOTGRNT', 'SDOTCOLNUM', 
              'SPEEDING', 'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR','SEVERITYCODE.1'], axis = 1, inplace=True)

### Removing Missing Data

In [4]:
missing_data = df_data.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")   
    
df_data.dropna(axis=0, inplace=True)

SEVERITYCODE
False    194673
Name: SEVERITYCODE, dtype: int64

ADDRTYPE
False    192747
True       1926
Name: ADDRTYPE, dtype: int64

LOCATION
False    191996
True       2677
Name: LOCATION, dtype: int64

INCDTTM
False    194673
Name: INCDTTM, dtype: int64

JUNCTIONTYPE
False    188344
True       6329
Name: JUNCTIONTYPE, dtype: int64

WEATHER
False    189592
True       5081
Name: WEATHER, dtype: int64

ROADCOND
False    189661
True       5012
Name: ROADCOND, dtype: int64

LIGHTCOND
False    189503
True       5170
Name: LIGHTCOND, dtype: int64

### Converting INCDTTM into useful features

In [5]:
df_data['INCDTTM'] = pd.to_datetime(df_data['INCDTTM'])

b = [0,4,8,12,16,20,24]
l = ['Late Night', 'Early Morning','Morning','Noon','Eve','Night']
df_data['TIME'] = pd.cut(df_data['INCDTTM'].dt.hour, bins=b, labels=l, include_lowest=True)
df_data['WEEKEND'] = df_data['INCDTTM'].dt.weekday>=5

def findHoliday(date):
    us_holidays = holidays.US()
    return date in us_holidays

df_data['HOLIDAY'] = df_data['INCDTTM'].apply(findHoliday)

df_data.drop(['INCDTTM'], axis = 1, inplace=True)


df_data.head()

,SEVERITYCODE,ADDRTYPE,LOCATION,JUNCTIONTYPE,WEATHER,ROADCOND,LIGHTCOND,TIME,WEEKEND,HOLIDAY
0,2,Intersection,5TH AVE NE AND NE 103RD ST,At Intersection (intersection related),Overcast,Wet,Daylight,Noon,False,False
1,1,Block,AURORA BR BETWEEN RAYE ST AND BRIDGE WAY N,Mid-Block (not related to intersection),Raining,Wet,Dark - Street Lights On,Eve,False,False
2,1,Block,4TH AVE BETWEEN SENECA ST AND UNIVERSITY ST,Mid-Block (not related to intersection),Overcast,Dry,Daylight,Morning,False,False
3,1,Block,2ND AVE BETWEEN MARION ST AND MADISON ST,Mid-Block (not related to intersection),Clear,Dry,Daylight,Morning,False,False
4,2,Intersection,SWIFT AVE S AND SWIFT AV OFF RP,At Intersection (intersection related),Raining,Wet,Daylight,Early Morning,False,False